version: '3.8'

services:
  offshoreproxy:
    build:
      context: .
      dockerfile: docker/offshoreproxy/Dockerfile.offshoreproxy
    ports:
      - "9090:9090"
    networks:
      - proxy_network

  shipproxy:
    build:
      context: .
      dockerfile: docker/shipproxy/Dockerfile.shipproxy
    ports:
      - "8080:8080"
    networks:
      - proxy_network
    depends_on:
      - offshoreproxy

networks:
  proxy_network:
    driver: bridge
